### ISSUE TITLE
Web site unreachable

### ISSUE THREAD

**Issue by ryandesign** [moses-smt/mgiza#15]
Your web site is unreachable.

    $ curl http://www.kyloo.net/software/
    curl: (7) Failed to connect to www.kyloo.net port 80: Network is unreachable

**Comment by hieuhoang** [comment]
this github repository is the only semi-maintained, up-to-date version of mgiza, as far as I know. The other URL is old

Will close this issue unless there are objections or further questions

**Comment by ryandesign** [comment]
That URL is the one printed at the top of this GitHub project's main page. If that URL is no longer useful, could you remove it from this GitHub project's page?

**Comment by hieuhoang** [comment]
ah of course. Done

**Comment by ryandesign** [comment]
Thanks!
