### ISSUE TITLE
library not found for -lrt

### ISSUE THREAD

**Issue by LeonIdeal** [moses-smt/mgiza#18]
Hi, when I follow the steps `cmake .`  and `make`
It runs with the error 

[ 51%] Linking CXX executable ../bin/d4norm
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/d4norm] Error 1
make[1]: *** [src/CMakeFiles/d4norm.dir/all] Error 2
make: *** [all] Error 2

I wonder how to solve this problem, thanks!

**Comment by hieuhoang** [comment]
apologires, too late for you but maybe useful for others in the future. MacOS doesn't have rt library so it will fail on link on the mac. Just comment mention of the rt lib from the Makefile
