### ISSUE TITLE
mgiza goes segmentation fault when USER environment variable is not set

### ISSUE THREAD

**Issue by aijanai** [moses-smt/mgiza#4]
The issue is in *Get_File_Spec()* function, in *mgizapp/src/file_spec.h*: 
calling ***user = getenv("USER");*** when USER variable is not set causes a segmentation fault.

I worked it around by calling *export USER='www-data'* (I was invoking the training chain from within a PHP script), but is this really necessary just to write a log file?

**Comment by hieuhoang** [comment]
You're right, it should be set to an arbitrary string if the username isn't found. If you make the code change, please send the code to me & i'll commit it. Otherwise, i'll do it in the next few days

**Comment by hieuhoang** [comment]
fixed by Matjaz Rihtar
  https://github.com/mrihtar/mgiza/commit/2b2bfbcb9dfe1f509f13597f186f01367c965b84
